spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password:  ${DB_PASSWORD}

#    for refresh without restart

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    bus:
      enabled: true

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"



app:
  message: "hello mitttarrr"
