spring:

#mongoDb connection
  data:
    mongodb:
      # this one is for the mongoDb compass which I have installed in local machine, and that one is for cloud mongodb
      uri: ${MONGO_URI}

#      this is for online version remote version of mongoDb I will stick to the local
#      uri: ${DB_URL}
      database: userdb


#postgres database connection

#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect


#h2 database connection

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8082
